# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd343f441fb980cfc156c89b21666244e27d1c0c48f6a5a2d7175970b0b13f0e38c619a70fb2800d3a8201c6b060373fe1a6cb3e551dc00290921d95079231df

test:
  secret_key_base: d2c9e4878559bc404c33808b67f87b5367f891ffcf71ccd68ca61a2ba732ebcbae6e695333a82293cac85bf1c5e9d96d8045c5bca3d1f4cf7a79961554a52d1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
